<h2>Thumbnail Generator</h2>

<script>
    var Chayka = window.Chayka || {};
    Chayka.Facebook = Chayka.Facebook || {};
    Chayka.Facebook.ThumbnailGenerator = <?php $this->json([
        'fonts' => $this->fonts,
        'defaultFont' => $this->defaultFont,
        'defaultLogo' => $this->defaultLogo,
        'defaultBackground' => $this->defaultBackground,
        'defaultSiteThumbnail' => $this->defaultSiteThumbnail,
        'defaultPostThumbnail' => $this->defaultPostThumbnail,
        'defaultTaxonomyThumbnail' => $this->defaultTaxonomyThumbnail,
        'thumbnailWidth' => $this->thumbnailWidth,
        'thumbnailHeight' => $this->thumbnailHeight,
        'templates' => $this->templates,
        'blocks' => $this->blocks,
        'postTypes' => $this->postTypes,
        'taxonomies' => $this->taxonomies
    ]);?>;

</script>

<div data-ng-cloak>
    <div data-thumbnail-setup>
    </div>
</div>