<?php //use Chayka\Helpers\Util; ?>
<div class="metabox" data-ng-cloak data-ng-controller="metabox">
	<div data-form-validator="validator">
        <?php /* fb_title */
        use Chayka\Facebook\ThumbnailHelper;
        use Chayka\Helpers\Util;

        $name      = 'metabox-fb_title';
            $value = $this->post->getMeta('fb_title');
        ?>
		<div class="form_field fullsize fb_title" data-form-field="fb_title">
			<label class="">Title (og:title)</label><input name = "<?php echo $name;?>" type="text" data-ng-init="meta.fb_title='<?php $this->escape($value); ?>' || ''" data-ng-model="meta.fb_title" title="Title (og:title)"/>
		</div>
        <?php /* fb_description */
            $name = 'metabox-fb_description';
            $value = $this->post->getMeta('fb_description');
        ?>
		<div class="form_field fullsize fb_description" data-form-field="fb_description">
			<label  class="">Description (og:description)</label><textarea name = "<?php echo $name;?>" data-ng-init="meta.fb_description='<?php $this->escape($value); ?>' || ''" data-ng-model="meta.fb_description" title="Description (og:description)"></textarea>
		</div>
        <?php /* fb_thumbnail */
//            $name = 'metabox-fb_thumbnail';
//            $value = $this->post->getMeta('fb_thumbnail');
//            wp_enqueue_media();
        ?>
        <!--div class="form_field fullsize fb_thumbnail" data-form-field="fb_thumbnail">
            <label class="">Thumbnail (og:image)</label>
            <input name="<?php echo $name;?>" value="{{meta.fb_thumbnail}}" type="hidden" data-ng-init="meta.fb_thumbnail='<?php $this->escape($value); ?>'" data-ng-model="meta.fb_thumbnail" title="Thumbnail (og:image)"/>
            <div data-media-picker data-mode="id" data-size="full" data-model="meta.fb_thumbnail" data-picker-button-text="Pick Image" data-title="Thumbnail" >
                Recommended: 1200 x 630px, min: 600 x 315
            </div>
        </div-->
        <?php /* fb_thumbnail */
        wp_enqueue_media();
        $thumbnailLayout = $this->post->getMeta('fb_thumbnail_layout');
        $templates = ThumbnailHelper::getTemplates();

        if(!$thumbnailLayout && $templates){
            $postTemplates = Util::getItem($templates, 'post', []);
            if($postTemplates){
                $thumbnailLayout = key($postTemplates);
            }
        }
        if(!$thumbnailLayout){
            $thumbnailLayout = 'featured';
        }
        $customThumbnail = $this->post->getMeta('fb_thumbnail_custom');
        $customThumbnail = $customThumbnail ? json_decode($customThumbnail, true) : '';
        ?>
        <script>
            var Chayka = window.Chayka || {};
            Chayka.Facebook = Chayka.Facebook || {};
            Chayka.Facebook.ThumbnailGenerator = <?php $this->json([
                'fonts' => $this->fonts,
                'defaultFont' => $this->defaultFont,
                'defaultLogo' => $this->defaultLogo,
                'defaultBackground' => $this->defaultBackground,
                'templates' => $this->templates,
                'blocks' => $this->blocks,
                'thumbnailWidth' => $this->thumbnailWidth,
                'thumbnailHeight' => $this->thumbnailHeight,
            ]);?>;

        </script>

        <div class="form_field fullsize fb_thumbnail_mode" data-form-field="fb_thumbnail_mode">
            <label class="">Thumbnail (og:image)</label>
            <input name="metabox-fb_thumbnail_layout" value="{{meta.fb_thumbnail_layout }}" type="hidden" data-ng-init="meta.fb_thumbnail_layout='<?php echo $thumbnailLayout ?>';" data-ng-model="meta.fb_thumbnail_layout" title="Thumbnail (og:image)"/>
            <input name="metabox-fb_thumbnail_custom" value="{{meta.fb_thumbnail_custom | json }}" type="hidden" data-ng-init="meta.fb_thumbnail_custom=<?php $this->json($customThumbnail, true); ?>;" data-ng-model="meta.fb_thumbnail_custom" title="Thumbnail (og:image)"/>
            <div data-post-thumbnail-editor data-custom-template="meta.fb_thumbnail_custom" data-layout="meta.fb_thumbnail_layout"></div>
        </div>


        <!-- chayka: fields -->
    </div>
</div>
