<div class="metabox">
    <?php /* fb_title */
    	$name = 'metabox-fb_title';
		$value = $this->post->getMeta('fb_title');
    ?>    
    <div class="form_field fullsize fb_title">
        <label  class="">Title (og:title)</label>
        <span class="input"><?php echo $this->formInput($name, $value, 'text', array());?></span>
        <div class="message"></div>
    </div>
    <?php /* fb_description */
    	$name = 'metabox-fb_description';
		$value = $this->post->getMeta('fb_description');
    ?>    
    <div class="form_field fullsize fb_description">
        <label  class="">Description (og:description)</label>
        <span class="input"><?php echo $this->formTextarea($name, $value);?></span>
        <div class="message"></div>
    </div>

    <!-- chayka: fields -->
</div>
