<?php //use Chayka\Helpers\Util; ?>
<div class="metabox" data-ng-cloak data-ng-controller="metabox">
	<div data-form-validator="validator">
        <?php /* fb_title */
            $name      = 'metabox-fb_title';
            $value = $this->post->getMeta('fb_title');
        ?>
		<div class="form_field fullsize fb_title" data-form-field="fb_title">
			<label class="">Title (og:title)</label><input name = "<?php echo $name;?>" type="text" data-ng-init="meta.fb_title='<?php $this->escape($value); ?>' || ''" data-ng-model="meta.fb_title" title="Title (og:title)"/>
		</div>
        <?php /* fb_description */
            $name = 'metabox-fb_description';
            $value = $this->post->getMeta('fb_description');
        ?>
		<div class="form_field fullsize fb_description" data-form-field="fb_description">
			<label  class="">Description (og:description)</label><textarea name = "<?php echo $name;?>" data-ng-init="meta.fb_description='<?php $this->escape($value); ?>' || ''" data-ng-model="meta.fb_description" title="Description (og:description)"></textarea>
		</div>
        <?php /* fb_thumbnail */
//            $name = 'metabox-fb_thumbnail';
//            $value = $this->post->getMeta('fb_thumbnail');
//            wp_enqueue_media();
        ?>
        <!--div class="form_field fullsize fb_thumbnail" data-form-field="fb_thumbnail">
            <label class="">Thumbnail (og:image)</label>
            <input name="<?php echo $name;?>" value="{{meta.fb_thumbnail}}" type="hidden" data-ng-init="meta.fb_thumbnail='<?php $this->escape($value); ?>'" data-ng-model="meta.fb_thumbnail" title="Thumbnail (og:image)"/>
            <div data-media-picker data-mode="id" data-size="full" data-model="meta.fb_thumbnail" data-picker-button-text="Pick Image" data-title="Thumbnail" >
                Recommended: 1200 x 630px, min: 600 x 315
            </div>
        </div-->
        <?php /* fb_thumbnail */
        $name = 'metabox-fb_thumbnail';
        $value = $this->post->getMeta('fb_thumbnail');
        $this->post->loadTerms();
        /**
         * @var \Chayka\WP\Models\PostModel $p
         */
        $p      = $this->post;
        $blocks = [
            'title' => $p->getTitle(),
            'excerpt' => $p->getExcerpt(),
            'categories' => join(', ', $p->getTerms('category')),
            'tags' => join(', ', $p->getTerms('post_tag')),
        ];

        $def = [
            'background' => '',
            'logo' => '',
            'fade' => [
                'color' => '#000000',
                'opacity' => 50
            ]
        ];

        foreach($blocks as $block=>$text){
            $def[$block] = [
                'active' => 'title' === $block,
                'color' => '#FFFFFF',
                'size' => 20
            ];
        }

        if(!$value){
            $value = $def;
        }else{
            $value = array_merge($def, json_decode($value, true));
        }

        $this->declareVars(['fonts' => []]);

        wp_enqueue_media();
        ?>
        <div class="form_field fullsize fb_thumbnail" data-form-field="fb_thumbnail">
            <label class="">Thumbnail (og:image)</label>
            <input name="<?php echo $name;?>" value="{{meta.fb_thumbnail | json}}" type="hidden" data-ng-init="meta.fb_thumbnail=<?php $this->json($value, true); ?>; postData=<?php $this->json($blocks, true); ?>; fonts = <?php $this->json($this->fonts, true); ?>;" data-ng-model="meta.fb_thumbnail" title="Thumbnail (og:image)"/>
            <div data-facebook-thumbnail-generator data-model="meta.fb_thumbnail" data-blocks="postData" data-fonts="fonts"></div>
        </div>



        <!-- chayka: fields -->
    </div>
</div>
