<?php
namespace Chayka\Facebook;

$this->declareVars([
	'locale' => 'en-US',
]);

$localSdk = Plugin::getInstance()->getUrlRes('lib/facebook/sdk.'.$this->locale.'.js');
$this->locale = str_replace('-', '_', $this->locale);
$remoteSdk = "//connect.facebook.net/".$this->locale."/sdk.js";
$sdkSrc = OptionHelper::getOption('jsSdkSource', 'remote') === 'remote'?$remoteSdk:$localSdk;

?>
<script>
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '<?php echo $this->appId;?>',
			status     : <?php echo FacebookHelper::isStatusChecked()?'true':'false'?>, // check login status
			cookie     : <?php echo FacebookHelper::isCookieCreated()?'true':'false'?>, // enable cookies to allow the server to access the session
			xfbml      : <?php echo FacebookHelper::isWidgetsRenderEnabled()?'true':'false'?>,  // parse XFBML
			version    : 'v2.2'
		});
	};

	(function(d, s, id){
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {return;}
		js = d.createElement(s); js.id = id;
		js.src = "<?php echo $sdkSrc;?>";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>