<?php
namespace Chayka\Facebook;

$this->declareVars([
	'locale' => 'en_US',
]);
?>
<script>
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '<?php echo $this->appId;?>',
			status     : <?php echo FacebookHelper::isStatusChecked()?'true':'false'?>, // check login status
			cookie     : <?php echo FacebookHelper::isCookieCreated()?'true':'false'?>, // enable cookies to allow the server to access the session
			xfbml      : <?php echo FacebookHelper::isWidgetsRenderEnabled()?'true':'false'?>,  // parse XFBML
			version    : 'v2.2'
		});
	};

	(function(d, s, id){
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {return;}
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/<?php echo $this->locale;?>/sdk.js";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>